# Create an .env file in the same folder, in order to specify USER and PASSWORD
version: '3'
services:
  bodega-db:
    image: mysql/mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=$USER
      - MYSQL_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=bodega

  query-runner:
    image: mysql/mysql-server
    depends_on:
      - bodega-db
    volumes:
      - ./sql-queries:/sql-queries
    command: ["sh", "-c", "sleep 30 && mysql -h bodega-db -u $USER -p$PASSWORD bodega -e 'source /sql-queries/init-db.sql'"]